# Generated by Django 3.2.4 on 2021-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=20, verbose_name='カテゴリ名英語'),
        ),
    ]
